version: '2.3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./es_data
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - kmnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 5

  ingest_elastic:
      build: .
      networks:
        - kmnet
#      command: "tail -f /dev/null"
      command: "wait-for-it -s es01:9200 -s km_postgres:5432 -- python index_pubmed.py bulk --n_min 1 --n_max 5"
      depends_on:
        - es01
      environment:
        - PYTHONUNBUFFERED=1

  postgres:
      container_name: km_postgres
      restart: always
      image: postgres:latest
      environment:
          - POSTGRES_PASSWORD=supersecretpassword
          - POSTGRES_USER=kinderminer
      volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - type: bind
            source: ./allie_data
            target: /var/lib/postgresql/data
      networks:
        - kmnet
      ports:
        - "5432:5432"

volumes:
  esdata01:
    driver: local

networks:
  kmnet:
